version: "3.8"

services:
  mongo:
    image: davybello/mongo-replica-set:5.0.12
    container_name: mongo-student-management-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: student_management

volumes:
  mongo_data:
